name: Release Version

on:
  push:
    tags:
      - "v*"

jobs:
  # Publish Python package to PyPI.
  publish-to-pypi:
    name: Publish to PyPI

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/ephys-link
    
    permissions:
      id-token: write
    
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: ğŸ“¦ Install Hatch
        uses: pypa/hatch@install

      - name: ğŸ”¨ Build Package
        run: hatch build

      - name: ğŸ“¦ Publish Distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  
  # Build Windows executable and make release.
  build-and-release:
    name: Build Executable and Release
    
    runs-on: windows-latest
    
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: ğŸ“¦ Install Hatch
        uses: pypa/hatch@install

      - name: ğŸ”¨ Build Executable
        run: hatch run exe

      - name: ğŸ¤ Zip Build Folder
        # FIXME: Need correct CLI with correct folder name.
        run: Compress-Archive -Path dist/ephys-link-${{ github.ref_name }} -Destination dist/ephys-link-${{ github.ref_name }}.zip

      - name: ğŸ“¦ Make Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          # FIXME: Use correct name.
          artifacts: "dist/ephys-link-${{ github.ref_name }}.zip,dist/ephys-link-${{ github.ref_name }}.exe"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref_name, "a") || contains(github.ref_name, "b") || contains(github.ref_name, "c") || contains(github.ref_name, "d") }}
